#include "agent_loop.h"
#include "agent/context_builder.h"
#include "agent_conf.h"
#include "bus/message_bus.h"
#include "llm/llm_proxy.h"
#include "memory/session_mgr.h"
#include "agent_tlsf.h"
#include "tools/tool_registry.h"
#if AGENT_CONSOLE_ENABLE
#include "console/agent_console.h"
#endif

#include <string.h>
#include <stdlib.h>
#include <pthread.h>
#include <stdbool.h>
#include "cJSON/cJSON.h"


#define TOOL_OUTPUT_SIZE  (8 * 1024)

/* Build the assistant content array from llm_response_t for the messages history.
 * Returns a cJSON array with text and tool_use blocks. */
static cJSON *build_assistant_content(const llm_response_t *resp)
{
    cJSON *content = cJSON_CreateArray();

    /* Text block */
    if(resp->text && resp->text_len > 0)
    {
        cJSON *text_block = cJSON_CreateObject();
        cJSON_AddStringToObject(text_block, "type", "text");
        cJSON_AddStringToObject(text_block, "text", resp->text);
        cJSON_AddItemToArray(content, text_block);
    }

    /* DeepSeek 思考模式推理内容（reasoning_content）。
     * 以 type="reasoning" 块存入 content 数组，
     * convert_messages_openai_compat() 会提取并放到 assistant 消息的
     * 顶层 reasoning_content 字段，满足 DeepSeek API 要求。 */
    if(resp->reasoning && resp->reasoning_len > 0)
    {
        cJSON *reasoning_block = cJSON_CreateObject();
        cJSON_AddStringToObject(reasoning_block, "type", "reasoning");
        cJSON_AddStringToObject(reasoning_block, "reasoning_content", resp->reasoning);
        cJSON_AddItemToArray(content, reasoning_block);
    }

    /* Tool use blocks */
    for(int i = 0; i < resp->call_count; i++)
    {
        const llm_tool_call_t *call = &resp->calls[i];
        cJSON *tool_block = cJSON_CreateObject();
        cJSON_AddStringToObject(tool_block, "type", "tool_use");
        cJSON_AddStringToObject(tool_block, "id", call->id);
        cJSON_AddStringToObject(tool_block, "name", call->name);

        cJSON *input = cJSON_Parse(call->input);
        if(input)
        {
            cJSON_AddItemToObject(tool_block, "input", input);
        }
        else
        {
            cJSON_AddItemToObject(tool_block, "input", cJSON_CreateObject());
        }

        cJSON_AddItemToArray(content, tool_block);
    }

    return content;
}

static void json_set_string(cJSON *obj, const char *key, const char *value)
{
    if(!obj || !key || !value)
    {
        return;
    }
    cJSON_DeleteItemFromObject(obj, key);
    cJSON_AddStringToObject(obj, key, value);
}

static bool is_cron_task_content(const char *content)
{
    size_t prefix_len = strlen(AGENT_CRON_TASK_PREFIX);
    return content && strncmp(content, AGENT_CRON_TASK_PREFIX, prefix_len) == 0;
}

static size_t bounded_strlen(const char *text, size_t max_len)
{
    size_t len = 0;
    while(len < max_len && text[len] != '\0')
    {
        len++;
    }
    return len;
}

static void append_turn_context_prompt(char *prompt, size_t size, const bus_msg_t *msg)
{
    if(!prompt || size == 0 || !msg)
    {
        return;
    }

    size_t off = bounded_strlen(prompt, size - 1);
    if(off >= size - 1)
    {
        return;
    }

    int n = snprintf(
                prompt + off, size - off,
                "\n## Current Turn Context\n"
                "- source_channel: %s\n"
                "- source_chat_id: %s\n"
                "- If using cron_add in this turn, set channel to source_channel and chat_id to source_chat_id.\n"
                "- Never use chat_id 'cron' for user-facing reminders.\n",
                (msg->channel[0] ? msg->channel : "(unknown)"),
                (msg->chat_id[0] ? msg->chat_id : "(empty)"));
    if(n < 0 || (size_t)n >= (size - off))
    {
        prompt[size - 1] = '\0';
    }

    if(is_cron_task_content(msg->content))
    {
        off = bounded_strlen(prompt, size - 1);
        if(off < size - 1)
        {
            n = snprintf(
                    prompt + off, size - off,
                    "\n## Cron Task Handling\n"
                    "The current user message was generated by the local cron scheduler.\n"
                    "Treat the scheduled job message as work to perform for the user, not as a reminder to you.\n"
                    "For a plain reminder, reply directly with a short, friendly reminder.\n"
                    "For scheduled work that needs tools, use the appropriate tools and then report the result.\n"
                    "Do not call cron tools, list jobs, adjust schedules, or ask whether to create a reminder unless the scheduled job message explicitly requests schedule management.\n");
            if(n < 0 || (size_t)n >= (size - off))
            {
                prompt[size - 1] = '\0';
            }
        }
    }
}

static char *patch_tool_input_with_context(const llm_tool_call_t *call, const bus_msg_t *msg)
{
    if(!call || !msg || strcmp(call->name, "cron_add") != 0)
    {
        return NULL;
    }

    cJSON *root = cJSON_Parse(call->input ? call->input : "{}");
    if(!root || !cJSON_IsObject(root))
    {
        cJSON_Delete(root);
        root = cJSON_CreateObject();
    }
    if(!root)
    {
        return NULL;
    }

    bool changed = false;

    cJSON *channel_item = cJSON_GetObjectItem(root, "channel");
    const char *channel = cJSON_IsString(channel_item) ? channel_item->valuestring : NULL;

    if((!channel || channel[0] == '\0') && msg->channel[0] != '\0')
    {
        json_set_string(root, "channel", msg->channel);
        channel = msg->channel;
        changed = true;
    }

    if(channel && msg->chat_id[0] != '\0' &&
            strcmp(channel, msg->channel) == 0)
    {
        cJSON *chat_item = cJSON_GetObjectItem(root, "chat_id");
        const char *chat_id = cJSON_IsString(chat_item) ? chat_item->valuestring : NULL;
        if(!chat_id || chat_id[0] == '\0' || strcmp(chat_id, "cron") == 0)
        {
            json_set_string(root, "chat_id", msg->chat_id);
            changed = true;
        }
    }

    char *patched = NULL;
    if(changed)
    {
        patched = cJSON_PrintUnformatted(root);
        if(patched)
        {
            AGENT_LOG("Patched cron_add target to %s:%s", msg->channel, msg->chat_id);
        }
    }

    cJSON_Delete(root);
    return patched;
}

/* Build the user message with tool_result blocks */
static cJSON *build_tool_results(const llm_response_t *resp, const bus_msg_t *msg,
                                 char *tool_output, size_t tool_output_size)
{
    cJSON *content = cJSON_CreateArray();

    for(int i = 0; i < resp->call_count; i++)
    {
        const llm_tool_call_t *call = &resp->calls[i];
        const char *tool_input = call->input ? call->input : "{}";
        char *patched_input = patch_tool_input_with_context(call, msg);
        if(patched_input)
        {
            tool_input = patched_input;
        }

        /* Execute tool */
        tool_output[0] = '\0';
        tool_registry_execute(call->name, tool_input, tool_output, tool_output_size);
        agent_free(patched_input);

        AGENT_LOG("Tool %s result: %d bytes", call->name, (int)strlen(tool_output));

        /* Build tool_result block */
        cJSON *result_block = cJSON_CreateObject();
        cJSON_AddStringToObject(result_block, "type", "tool_result");
        cJSON_AddStringToObject(result_block, "tool_use_id", call->id);
        cJSON_AddStringToObject(result_block, "content", tool_output);
        cJSON_AddItemToArray(content, result_block);
    }

    return content;
}

/**
 * 流式文本输出回调。
 *
 * 每当 LLM API 通过 SSE 返回一段新的文本 token 时，本回调被调用。
 * 直接将文本片段输出到 stdout，实现逐字显示效果。
 *
 * 注意：此回调运行在 agent_loop 线程中，与 outbound_dispatch 线程并行。
 * 但由于 fwrite + fflush 是线程安全的，这里直接写 stdout 即可。
 *
 * @param text_delta  本次收到的文本片段
 * @param delta_len   片段长度
 * @param userp       未使用
 * @return 始终返回 0（继续流式读取）
 */
#if AGENT_LLM_STREAM_ENABLED
static int stream_output_cb(const char *text_delta, size_t delta_len, void *userp)
{
    (void)userp;

    if(text_delta && delta_len > 0)
    {
        fwrite(text_delta, 1, delta_len, stdout);
        fflush(stdout);
    }

    return 0;
}
#endif

static void *agent_loop_task(void *arg)
{
    (void)arg;
    AGENT_LOG("Agent loop started");

    char *system_prompt = agent_calloc(1, AGENT_CONTEXT_BUF_SIZE);
    char *history_json = agent_calloc(1, AGENT_LLM_STREAM_BUF_SIZE);
    char *tool_output = agent_calloc(1, TOOL_OUTPUT_SIZE);

    if(!system_prompt || !history_json || !tool_output)
    {
        AGENT_LOG("Failed to allocate buffers");
        agent_free(system_prompt);
        agent_free(history_json);
        agent_free(tool_output);
        return NULL;
    }

    const char *tools_json = tool_registry_get_tools_json();

    while(1)
    {
        bus_msg_t msg;
        /*
         * pop 返回的 msg.content 是 message_bus 内部 ring buffer 的借用指针。
         * 本轮处理期间可以直接读取；循环末尾必须 release，释放 inbound 队列空间。
         */
        int len_context = message_bus_pop_inbound(&msg, UINT32_MAX);
        if(len_context <= 0)
        {
            continue;
        }

        AGENT_LOG("Processing message from %s:%s", msg.channel, msg.chat_id);
        bool cron_task = is_cron_task_content(msg.content);

        /* 1. Build system prompt */
        context_build_system_prompt(system_prompt, AGENT_CONTEXT_BUF_SIZE);
        append_turn_context_prompt(system_prompt, AGENT_CONTEXT_BUF_SIZE, &msg);
        AGENT_LOG("LLM turn context: channel=%s chat_id=%s", msg.channel, msg.chat_id);

        /* 2. Load session history into cJSON array */
        if(cron_task)
        {
            snprintf(history_json, AGENT_LLM_STREAM_BUF_SIZE, "[]");
        }
        else
        {
            session_get_history_json(msg.channel, msg.chat_id, history_json,
                                     AGENT_LLM_STREAM_BUF_SIZE, AGENT_MAX_HISTORY);
        }

        cJSON *messages = cJSON_Parse(history_json);
        if(!messages)
        {
            messages = cJSON_CreateArray();
        }

        /* 3. Append current user message */
        cJSON *user_msg = cJSON_CreateObject();
        cJSON_AddStringToObject(user_msg, "role", "user");
        cJSON_AddStringToObject(user_msg, "content", msg.content);
        cJSON_AddItemToArray(messages, user_msg);

        /* 4. ReAct loop */
        char *final_text = NULL;
        int iteration = 0;
        bool sent_working_status = false;
        bool had_tool_iter = false;    /* 本轮是否发生过工具调用 */
        char *final_reasoning = NULL;  /* 最终回答的推理内容（DeepSeek 思考模式） */
        /* 在 ReAct 循环开始前先持久化用户消息。
         * 这样即使在工具调用迭代中，session 文件里的消息顺序也是正确的：
         * user → assistant(tool_calls) → tool results → ... → assistant(final)
         * cron 任务不需要保存 session。 */
        if(!cron_task)
        {
            session_append(msg.channel, msg.chat_id, "user", msg.content);
        }

        while(iteration < AGENT_MAX_TOOL_ITER)
        {
            /*
             * 发送 "working" 状态指示。
             *
             * 在 LLM API 调用前通过 outbound 通道发送 "agent is working..."，
             * 让用户知道请求正在处理中（尤其是非 CLI 通道，如微信、Telegram，
             * 用户无法看到本地控制台的实时输出）。
             *
             * CLI 通道 + 流式输出的交错问题：
             *
             * CLI 通道的 outbound 消息通过 agent_console_send_message() 处理，
             * 它会打印 "agent[xxx]: agent is working..." 并立即显示提示符 "> "。
             * 随后 llm_chat_stream() 的 stream_output_cb 直接往 stdout 写 token，
             * 导致回答出现在提示符后面。流式输出结束后又会再打印一次提示符。
             * 最终显示效果：
             *   > 用户输入
             *   agent[console]:
             *   agent is working...
             *   > 流式回答内容出现在这里...   ← 被夹在提示符之间
             *   >
             *
             * 修复：当 CLI 通道 + 流式模式同时生效时，跳过 working 状态推送。
             * 流式输出本身就能让用户看到实时响应，不需要额外的 working 提示。
             * 非 CLI 通道（微信、Telegram 等）不受影响，仍保留 working 状态。
             */
#if AGENT_SEND_WORKING_STATUS
            if(!cron_task && !sent_working_status && strcmp(msg.channel, CHANNEL_SYSTEM) != 0)
            {
#if AGENT_LLM_STREAM_ENABLED
                /* 流式 CLI 通道跳过 working 状态，避免与流式输出交错 */
                bool skip_working = (strcmp(msg.channel, CHANNEL_CLI) == 0);
#else
                bool skip_working = false;
#endif
                if(!skip_working)
                {
                    bus_msg_t status;
                    bus_msg_set(&status, msg.channel, msg.chat_id, "agent is working...");
                    if(message_bus_push_outbound(&status) != 0)
                    {
                        AGENT_LOG("Outbound push failed, drop working status");
                    }
                    else
                    {
                        sent_working_status = true;
                    }
                }
                else
                {
                    /* CLI 流式模式：标记为已发送，后续迭代也不再尝试 */
                    sent_working_status = true;
                }
            }
#endif

            llm_response_t resp = {0};   /* 零初始化：确保 stream_had_output 等标志从 false 开始 */

            /*
             * 调用 LLM API。
             *
             * 流式模式下使用 llm_chat_stream()：
             * - 文本 token 逐个通过 stream_output_cb 回调输出到 stdout
             * - 完整文本仍累积在 resp.text 中，供后续 session 保存和 outbound 推送
             * - 工具调用也通过 SSE 增量解析，累积到 resp.calls[]
             *
             * 如果流式未启用（AGENT_LLM_STREAM_ENABLED=0），回退到非流式调用。
             */
#if AGENT_LLM_STREAM_ENABLED
            int err = llm_chat_stream(system_prompt, messages, tools_json,
                                      stream_output_cb, NULL, &resp);
#else
            int err = llm_chat_tools(system_prompt, messages, tools_json, &resp);
#endif

            if(err != 0)
            {
                AGENT_LOG("LLM call failed: %d", err);

                /*
                 * 流式输出异常时的 CLI 提示。
                 *
                 * 问题：parse_sse_event 在收到 content delta 时立即通过
                 * stream_output_cb 输出到 stdout。但如果后续 finish_reason
                 * 为 "length"（截断）、"content_filter"（过滤）或流内 error，
                 * 之前已经显示给用户的内容实际上是无效的。
                 *
                 * 由于 stdout 不可回退，我们无法撤回已显示的内容。
                 * 解决方案：在已输出内容后打印一条醒目的错误提示，
                 * 让用户知道上面的内容不完整或不可用。
                 *
                 * stream_had_output 标记由 parse_sse_event 设置：
                 * 仅当 on_chunk 回调被实际调用过时才为 true，
                 * 避免在无输出时就打印错误提示。
                 */
#if AGENT_LLM_STREAM_ENABLED
                if(resp.stream_had_output)
                {
                    fputs("\n[输出异常终止，以上内容可能不完整]\n", stdout);
                    fflush(stdout);
                }
#endif
                /*
                 * 【内存泄漏修复】释放 resp 中可能已分配的资源。
                 *
                 * llm_chat_stream() / llm_chat_tools() 失败时（如网络中断、
                 * JSON 解析错误），resp 中可能已经累积了部分数据：
                 * - resp.text: 流式过程中已收到的文本增量
                 * - resp.reasoning: DeepSeek 思考模式的推理内容
                 * - resp.calls[i].input: 工具调用参数（增量追加）
                 *
                 * 如果不调用 llm_response_free()，这些由 TLSF 分配器
                 * 分配的堆内存就不会被归还。在流式网络错误反复发生时
                 * （如 API 服务不稳定），TLSF 内存池会被逐渐耗尽，
                 * 最终导致 agent_malloc 失败、消息处理完全停止。
                 */
                llm_response_free(&resp);
                break;
            }

            if(!resp.tool_use)
            {
                /* 正常完成 — 保存最终文本并退出循环 */
#if AGENT_LLM_STREAM_ENABLED
                /* 流式输出结束后换行，让后续控制台提示符出现在新行 */
                if(resp.text_len > 0)
                {
                    fputs("\n", stdout);
                    fflush(stdout);
                }
#endif
                if(resp.text && resp.text_len > 0)
                {
                    final_text = agent_strdup(resp.text);
                }

                /* 如果本轮发生过工具调用且最终回答包含推理内容，
                 * 在释放 resp 前先捕获，避免 reasoning_content 丢失。
                 * DeepSeek 要求每个 assistant message 都回传 reasoning_content，
                 * 包括工具调用流程的最终回答。 */
                if(had_tool_iter && resp.reasoning && resp.reasoning_len > 0)
                {
                    final_reasoning = agent_strdup(resp.reasoning);
                }

                llm_response_free(&resp);
                break;
            }

            AGENT_LOG("Tool use iteration %d: %d calls", iteration + 1, resp.call_count);
            had_tool_iter = true;

            /* Append assistant message with content array */
            cJSON *asst_msg = cJSON_CreateObject();
            cJSON_AddStringToObject(asst_msg, "role", "assistant");
            cJSON_AddItemToObject(asst_msg, "content", build_assistant_content(&resp));
            cJSON_AddItemToArray(messages, asst_msg);

            /* Execute tools and append results */
            cJSON *tool_results = build_tool_results(&resp, &msg, tool_output, TOOL_OUTPUT_SIZE);
            cJSON *result_msg = cJSON_CreateObject();
            cJSON_AddStringToObject(result_msg, "role", "user");
            cJSON_AddItemToObject(result_msg, "content", tool_results);
            cJSON_AddItemToArray(messages, result_msg);

            /*
             * 持久化结构化消息到 session，确保跨用户轮次可重放。
             *
             * DeepSeek 思考模式要求：发生工具调用的轮次，后续请求必须
             * 完整回传 assistant 的 reasoning_content 和 tool_calls，
             * 否则 API 返回 400。
             *
             * 当前 ReAct 循环的 messages 数组在循环结束后被 cJSON_Delete
             * 释放，所以必须在循环内将结构化消息写入 session 文件。
             * session_get_history_json() 会保留这些字段，下次用户消息
             * 加载历史时，LLM API 就能收到完整的结构化上下文。
             *
             * asst_msg  包含 content blocks（含 reasoning 和 tool_use）
             * result_msg 包含 content blocks（含 tool_result）
             *
             * 写入失败时必须中断循环：
             * 如果只写了 assistant 消息（含 tool_calls）但没写 tool_result，
             * session 文件中会留下半条工具调用链。下次加载历史时，
             * DeepSeek API 会因缺少 tool_result 配对而返回 400。
             * 中断后让本轮工具调用不持久化，比留下残缺上下文更安全。
             */
            if(!cron_task)
            {
                /*
                 * 原子写入 assistant(tool_calls) + tool_result 到 session。
                 *
                 * 旧实现分两次调用 session_append_message_json()，存在以下风险：
                 * 1. assistant 写入成功，tool_result 写入失败 → 半条工具调用链
                 * 2. assistant 写入失败，tool_result 写入成功 → 孤儿 tool_result
                 * 3. 两种情况都会导致下次加载历史时 DeepSeek API 返回 400
                 *
                 * session_append_tool_chain() 在同一个文件句柄中写入两条记录，
                 * 第二条失败时通过 ftruncate 回滚到写入前的位置，
                 * 确保不会留下不完整的工具调用链。
                 */
                int sc = session_append_tool_chain(msg.channel, msg.chat_id,
                                                   asst_msg, result_msg);
                if(sc != 0)
                {
                    AGENT_LOG("Session atomic tool chain write failed (%d), "
                              "aborting ReAct loop", sc);
                    llm_response_free(&resp);
                    break;
                }
            }

            llm_response_free(&resp);
            iteration++;
        }

        cJSON_Delete(messages);

        /* 5. Send response */
        if(final_text && final_text[0])
        {
            if(!cron_task)
            {
                /* 如果本轮发生过工具调用，最终回答可能包含 reasoning_content，
                 * 需要用结构化消息持久化，确保跨轮次回传给 DeepSeek API。
                 * 否则 API 会因缺少 reasoning_content 返回 400。 */
                if(had_tool_iter)
                {
                    cJSON *final_asst = cJSON_CreateObject();
                    cJSON_AddStringToObject(final_asst, "role", "assistant");

                    cJSON *content_arr = cJSON_CreateArray();
                    if(final_text && final_text[0])
                    {
                        cJSON *tb = cJSON_CreateObject();
                        cJSON_AddStringToObject(tb, "type", "text");
                        cJSON_AddStringToObject(tb, "text", final_text);
                        cJSON_AddItemToArray(content_arr, tb);
                    }
                    if(final_reasoning)
                    {
                        cJSON *rb = cJSON_CreateObject();
                        cJSON_AddStringToObject(rb, "type", "reasoning");
                        cJSON_AddStringToObject(rb, "reasoning_content", final_reasoning);
                        cJSON_AddItemToArray(content_arr, rb);
                    }
                    cJSON_AddItemToObject(final_asst, "content", content_arr);

                    int save_asst = session_append_message_json(msg.channel, msg.chat_id, final_asst);
                    cJSON_Delete(final_asst);

                    if(save_asst != 0)
                    {
                        AGENT_LOG("Session save structured final failed (%d)", save_asst);
                    }
                    else
                    {
                        AGENT_LOG("Session saved (structured final) for chat %s", msg.chat_id);
                    }
                }
                else
                {
                    /* 无工具调用发生，直接用纯文本保存 */
                    int save_asst = session_append(msg.channel, msg.chat_id, "assistant", final_text);
                    if(save_asst != 0)
                    {
                        AGENT_LOG("Session save failed for chat %s (assistant=%d)",
                                  msg.chat_id, save_asst);
                    }
                    else
                    {
                        AGENT_LOG("Session saved for chat %s", msg.chat_id);
                    }
                }
            }
            else
            {
                AGENT_LOG("Skip session save for cron task %s:%s", msg.channel, msg.chat_id);
            }

            /* Outbound 推送：将最终文本推送到输出通道。
             *
             * 流式模式下 CLI channel 已通过 stream_output_cb 实时输出到 stdout，
             * 如果再推送完整文本，agent_console_send_message() 会再打印一遍，
             * 用户看到 "Hello world" 后紧接着又看到 "Hello world"。
             *
             * 其他 channel（如 weixin）需要完整文本推送（不支持流式），
             * 所以只对 CLI channel 跳过 outbound 推送。
             */
            {
                bool push_to_outbound = true;
#if AGENT_LLM_STREAM_ENABLED
                if(strcmp(msg.channel, CHANNEL_CLI) == 0)
                {
                    push_to_outbound = false;
                }
#endif
                if(push_to_outbound)
                {
                    bus_msg_t out;
                    bus_msg_set(&out, msg.channel, msg.chat_id, final_text);
                    AGENT_LOG("Queue final response to %s:%s (%d bytes)",
                              out.channel, out.chat_id, (int)strlen(final_text));
                    if(message_bus_push_outbound(&out) != 0)
                    {
                        AGENT_LOG("Outbound push failed, drop final response");
                        agent_free(final_text);
                    }
                    else
                    {
                        agent_free(final_text);
                        final_text = NULL;
                    }
                }
                else
                {
                    /* CLI channel 已通过 stream_output_cb 实时输出到 stdout，
                     * 不再推送完整文本（避免重复打印）。
                     *
                     * 【prompt 恢复修复】
                     *
                     * 非 CLI channel 的回复通过 outbound 队列发送，
                     * outbound_dispatch_task 调用 agent_console_send_message()
                     * 打印内容后会调用 console_print_prompt() 显示 "> " 提示符。
                     *
                     * 但 CLI channel 跳过了 outbound 推送，因此不会触发
                     * agent_console_send_message()，用户看到流式回答结束后
                     * 没有新的提示符，无法输入下一条消息。
                     *
                     * 修复：流式输出完成后直接打印 CLI 提示符。
                     * AGENT_CONSOLE_PROMPT 定义为 "> "（见 agent_console.c），
                     * 这里使用相同格式保持一致。
                     */
                    AGENT_LOG("Skip outbound for CLI (streamed to stdout)");
                    agent_free(final_text);
                    final_text = NULL;
                    /*
                     * 流式输出完成后恢复 CLI 提示符。
                     *
                     * 通过 agent_console_print_prompt() 调用，而非直接
                     * fputs("> ")，这样提示符样式由 agent_console.c 统一管理。
                     * 如果 AGENT_CONSOLE_PROMPT 从 "> " 改为其他样式（如
                     * "agent> " 或带 ANSI 颜色），只需修改 agent_console.c，
                     * 所有调用点自动同步。
                     *
                     * 当 AGENT_CONSOLE_ENABLE=0 时，该函数为空操作。
                     */
#if AGENT_CONSOLE_ENABLE
                    /*
                     * 仅在本地 console 功能被编译进镜像时恢复提示符。
                     * vx_global 默认不链接 console/agent_console.c，关闭该开关时这里
                     * 不能引用 agent_console_print_prompt()，否则最终链接会失败。
                     */
                    agent_console_print_prompt();
#endif
                }
            }
        }
        else
        {
            /* Error or empty response */
            agent_free(final_text);
            bus_msg_t out;
            bus_msg_set(&out, msg.channel, msg.chat_id, "Sorry, I encountered an error.");
            if(message_bus_push_outbound(&out) != 0)
            {
                AGENT_LOG("Outbound push failed, drop error response");
            }
        }

        /* 释放本轮捕获的推理内容副本 */
        agent_free(final_reasoning);

        /* 归还 inbound 消息租约；此后 msg.content 失效，不要再访问。 */
        message_bus_release(&msg);
    }

    return NULL;
}

int agent_loop_init(void)
{
    AGENT_LOG("Agent loop initialized");
    return 0;
}

int agent_loop_start(void)
{
    pthread_t agent_loop_thread = 0;

    if(0 != pthread_create(&agent_loop_thread, NULL, agent_loop_task, NULL))
    {
        AGENT_LOG("fail to create agent_loop_task");
        return -1;
    }

    return 0;
}
